[package]
name = "bento-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.21"
serde = "1.0.198"
libbento = { path = "../libbento" }
nix = "0.30.1"
libc = "0.2.174"
