[package]
name = "libbento"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["sched", "process", "hostname", "user", "fs", "mount"] }
libc = "0.2.174"
anyhow = "1.0.98"
